spring:
  application:
    name: coworkings

  datasource:
    url: jdbc:postgresql://localhost:5432/coworkings
    username: postgres
    password: Ab12345678.
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: Y293b3JraW5nc0FwcEBTZWNyZXRLZXkyMDI2IWNvd29ya2luZ3M=
      expiration: 21600000